# permissions for end users to view webservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nodejs-operator-example
    app.kubernetes.io/managed-by: kustomize
  name: webserver-viewer-role
rules:
- apiGroups:
  - web.example.com
  resources:
  - webservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.example.com
  resources:
  - webservers/status
  verbs:
  - get
