apiVersion: web.example.com/v1alpha1
kind: WebServer
metadata:
  labels:
    app.kubernetes.io/name: nodejs-operator-example
    app.kubernetes.io/managed-by: kustomize
  name: webserver-sample
spec:
  # TODO(user): Add fields here
